CREATE USER EMPLOYEE_CRUD IDENTIFIED BY EMPLOYEE_CRUD;
GRANT CONNECT, RESOURCE TO EMPLOYEE_CRUD;

CREATE TABLESPACE TS_EMPLOYEE_CRUD_DATA
  LOGGING
  DATAFILE '/usr/lib/oracle/xe/oradata/XE/TS_EMPLOYEE_CRUD_DATA.dbf'
  SIZE 32M;

CREATE TABLESPACE TS_EMPLOYEE_ID_INDEX
  LOGGING
  DATAFILE '/usr/lib/oracle/xe/oradata/XE/TS_EMPLOYEE_CRUD_INDEX.dbf'
  SIZE 32M;

CREATE SEQUENCE EMPLOYEE_CRUD.EMPLOYEE_SEQ;

CREATE TABLE EMPLOYEE_CRUD.EMPLOYEES (
  "EMPLOYEE_ID" NUMBER(5,0) NOT NULL,
  "FIRST_NAME" VARCHAR2(50) NOT NULL,
  "LAST_NAME"  VARCHAR2(50) NOT NULL,
  "SALARY"  NUMBER(8,2) NOT NULL,
  "ROLE"  VARCHAR2(50) NOT NULL,
  CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID") using index TABLESPACE TS_EMPLOYEE_ID_INDEX
) TABLESPACE TS_EMPLOYEE_CRUD_DATA;
